### ISSUE TITLE
Create database diagram

### ISSUE THREAD

**Issue by decant09** [kpetrauskas92/team5-feb-hackathon#21]
As a developer,

I want to create a database diagram,

So that I can have a clear outline of how the models of the project will be laid out and relate to each other.

**Tasks**

- [x] Decide on fields for each model
- [x] Determine relationship between models
- [x] Create diagram on lucidchart
