### ISSUE TITLE
Profile App

### ISSUE THREAD

**Issue by decant09** [kpetrauskas92/team5-feb-hackathon#31]
As a developer,

I want to create a profile app

So that,

I can store and access specific information regarding users of the website

**Tasks**

- [x] Create profile app
- [x] Add desired fields to profile model
- [x] Create template to display profile to user
