### ISSUE TITLE
Create user profile form

### ISSUE THREAD

**Issue by decant09** [kpetrauskas92/team5-feb-hackathon#66]
As a user,

I want to be able to view my profile data in a form,

So that,

I can update the data as desired

**Tasks**

- [x] Create a forms.py file
- [x] Create a view to handle the form
- [x] Add buttons to perform functions

**Comment by kpetrauskas92** [comment]
Done
